export const frameworks = [
  {
    id: 1,
    name: "SWOT Analysis",
    category: "Strategy",
    complexity: "Beginner",
    readTime: "15 min read",
    tag: "Strategic Planning",
    description:
      "Master your environment by identifying Strengths, Weaknesses, Opportunities, and Threats. The foundational tool for every high-stakes decision.",
    featured: true,
    workshop: true,
    tool: "swot",
  },
  {
    id: 2,
    name: "First Principles",
    category: "Strategy",
    complexity: "Intermediate",
    readTime: "10 min read",
    tag: "Strategy",
    description:
      "Breaking down complex problems into basic elements and then reassembling them from the ground up.",
    workshop: true,
    tool: "first_principles",
  },
  {
    id: 3,
    name: "The Hero's Journey",
    category: "Narrative",
    complexity: "Beginner",
    readTime: "8 min read",
    tag: "Narrative",
    description:
      "A structural framework for storytelling used to create compelling brand narratives and product visions.",
  },
  {
    id: 4,
    name: "Cynefin Framework",
    category: "Problem Solving",
    complexity: "Advanced",
    readTime: "15 min read",
    tag: "New Framework",
    description:
      "A decision-making tool used to help managers, policy-makers and others identify how they perceive situations and make sense of their own and other people's behavior.",
    isNew: true,
  },
  {
    id: 5,
    name: "5 Whys",
    category: "Problem Solving",
    complexity: "Beginner",
    readTime: "5 min read",
    tag: "Problem Solving",
    description:
      "An iterative interrogative technique used to explore the cause-and-effect relationships underlying a problem.",
  },
  {
    id: 6,
    name: "STAR Method",
    category: "Narrative",
    complexity: "Beginner",
    readTime: "6 min read",
    tag: "Communication",
    description: "Structure your responses to showcase leadership and impact under pressure.",
  },
  {
    id: 7,
    name: "Minto Pyramid",
    category: "Narrative",
    complexity: "Intermediate",
    readTime: "12 min read",
    tag: "Logical Thinking",
    description: "The gold standard for top-down logic and effective executive communication.",
    workshop: true,
    tool: "pyramid",
  },
  {
    id: 8,
    name: "Eisenhower Matrix",
    category: "Leadership",
    complexity: "Beginner",
    readTime: "5 min read",
    tag: "Leadership",
    description: "Prioritize what matters by sorting tasks along urgency and importance.",
  },
  {
    id: 9,
    name: "Porter's Five Forces",
    category: "Strategy",
    complexity: "Advanced",
    readTime: "14 min read",
    tag: "Strategy",
    description: "Analyze the competitive intensity and attractiveness of an industry.",
  },
  {
    id: 10,
    name: "OKR Planning",
    category: "Leadership",
    complexity: "Intermediate",
    readTime: "9 min read",
    tag: "Leadership",
    description: "Set ambitious objectives with measurable key results to align teams.",
  },
  {
    id: 11,
    name: "Issue Tree Builder",
    category: "Problem Solving",
    complexity: "Intermediate",
    readTime: "12 min read",
    tag: "Problem Solving",
    description:
      "Break a root question into mutually exclusive, collectively exhaustive branches on a pannable, zoomable canvas.",
    workshop: true,
    tool: "issue_tree",
  },
  {
    id: 12,
    name: "MECE Workspace",
    category: "Problem Solving",
    complexity: "Intermediate",
    readTime: "10 min read",
    tag: "Problem Solving",
    description:
      "Decompose a core problem into categories with live overlap and gap auditing, so nothing is double-counted or missed.",
    workshop: true,
    tool: "mece",
  },
  {
    id: 13,
    name: "SCQA Storytelling",
    category: "Narrative",
    complexity: "Beginner",
    readTime: "8 min read",
    tag: "Narrative",
    description:
      "Structure a tight pitch narrative — Situation, Complication, Question, Answer — with a live preview as you write.",
    workshop: true,
    tool: "scqa",
  },
  {
    id: 14,
    name: "Logic Tree Workshop",
    category: "Problem Solving",
    complexity: "Advanced",
    readTime: "14 min read",
    tag: "Diagnostics",
    description:
      "Diagnose symptoms or stress-test decisions on a branching canvas with live path-coverage and logic-fallacy scanning.",
    workshop: true,
    isNew: true,
    tool: "logic_tree",
  },
  {
    id: 15,
    name: "Systems Thinking Workspace",
    category: "Strategy",
    complexity: "Advanced",
    readTime: "18 min read",
    tag: "Causal Loop Canvas",
    description:
      "Map stocks, flows, and reinforcing/balancing feedback loops, then let the Delay/Feedback Analyzer surface leverage points.",
    workshop: true,
    isNew: true,
    tool: "systems_thinking",
  },
  {
    id: 16,
    name: "Hypothesis-Driven Thinking",
    category: "Strategy",
    complexity: "Intermediate",
    readTime: "12 min read",
    tag: "Validation",
    description:
      "Turn a business assumption into a testable hypothesis, design the test, and track confidence as evidence comes in.",
    workshop: true,
    isNew: true,
    tool: "hypothesis",
  },
  {
    id: 17,
    name: "GE McKinsey Matrix",
    category: "Strategy",
    complexity: "Advanced",
    readTime: "14 min read",
    tag: "Portfolio Analysis",
    description:
      "Plot business units on a 3x3 industry attractiveness vs. competitive strength grid to guide invest, hold, or divest decisions.",
    workshop: true,
    isNew: true,
    tool: "ge_mckinsey",
  },
  {
    id: 18,
    name: "Three Horizons Framework",
    category: "Strategy",
    complexity: "Advanced",
    readTime: "12 min read",
    tag: "Portfolio Planning",
    description:
      "Balance current-core, emerging, and future-option initiatives on a value-vs-time map with target allocation tracking.",
    workshop: true,
    isNew: true,
    tool: "three_horizons",
  },
  {
    id: 19,
    name: "Porter's Generic Strategies",
    category: "Strategy",
    complexity: "Intermediate",
    readTime: "10 min read",
    tag: "Competitive Strategy",
    description:
      "Define your strategic scope and advantage — Cost Leadership, Differentiation, or a Focused variant — and benchmark competitors.",
    workshop: true,
    isNew: true,
    tool: "porter",
  },
  {
    id: 20,
    name: "Strategic Choice Cascade",
    category: "Strategy",
    complexity: "Advanced",
    readTime: "16 min read",
    tag: "Playing to Win",
    description:
      "Work through Lafley & Martin's five cascading strategy choices, from Winning Aspiration down to Management Systems.",
    workshop: true,
    isNew: true,
    tool: "strategic_cascade",
  },
  {
    id: 21,
    name: "Core Competency Auditor",
    category: "Strategy",
    complexity: "Intermediate",
    readTime: "10 min read",
    tag: "Competitive Advantage",
    description:
      "Audit your capabilities against the Valuable, Unique, and Extendable test to find your true competitive moat.",
    workshop: true,
    isNew: true,
    tool: "core_competency",
  },
  {
    id: 22,
    name: "Lean Canvas Workshop",
    category: "Strategy",
    complexity: "Beginner",
    readTime: "10 min read",
    tag: "Business Model",
    description:
      "Sketch your business model across all nine Lean Canvas blocks, from Problem and Solution to Cost Structure and Revenue Streams.",
    workshop: true,
    isNew: true,
    tool: "lean_canvas",
  },
  {
    id: 23,
    name: "VRIO Analysis Workshop",
    category: "Strategy",
    complexity: "Advanced",
    readTime: "12 min read",
    tag: "Resource-Based View",
    description:
      "Test resources against Valuable, Rare, Inimitable, and Organized hurdles to determine sustained competitive advantage.",
    workshop: true,
    isNew: true,
    tool: "vrio",
  },
  {
    id: 24,
    name: "OKR Workshop",
    category: "Leadership",
    complexity: "Intermediate",
    readTime: "10 min read",
    tag: "Goal Setting",
    description:
      "Set an ambitious objective and track measurable key results with live confidence and progress tracking.",
    workshop: true,
    isNew: true,
    tool: "okr",
  },
  {
    id: 25,
    name: "Product Roadmap Workshop",
    category: "Leadership",
    complexity: "Intermediate",
    readTime: "12 min read",
    tag: "Execution",
    description:
      "Plan milestones across a four-quarter horizon with category tags, progress tracking, and roadmap health insights.",
    workshop: true,
    isNew: true,
    tool: "product_roadmap",
  },
  {
    id: 26,
    name: "Project Charter Workshop",
    category: "Leadership",
    complexity: "Intermediate",
    readTime: "14 min read",
    tag: "Project Initiation",
    description:
      "Define purpose, measurable objectives, milestones, success criteria, risks, and requirements for a new initiative.",
    workshop: true,
    isNew: true,
    tool: "project_charter",
  },
  {
    id: 27,
    name: "RACI Matrix Workshop",
    category: "Leadership",
    complexity: "Intermediate",
    readTime: "10 min read",
    tag: "Responsibility Assignment",
    description:
      "Clarify who is Responsible, Accountable, Consulted, and Informed across your cross-functional team.",
    workshop: true,
    isNew: true,
    tool: "raci",
  },
  {
    id: 28,
    name: "Retrospective Workshop",
    category: "Leadership",
    complexity: "Beginner",
    readTime: "8 min read",
    tag: "Team Health",
    description:
      "Run a Start, Stop, Continue retrospective with sticky-note voting and a shared action item checklist.",
    workshop: true,
    isNew: true,
    tool: "retrospective",
  },
  {
    id: 29,
    name: "Sprint Planning Workshop",
    category: "Leadership",
    complexity: "Intermediate",
    readTime: "10 min read",
    tag: "Agile",
    description:
      "Move stories from the product backlog into the sprint backlog with live capacity utilization and sprint health.",
    workshop: true,
    isNew: true,
    tool: "sprint_planning",
  },
  {
    id: 30,
    name: "Critical Path Analysis Workshop",
    category: "Leadership",
    complexity: "Advanced",
    readTime: "14 min read",
    tag: "Project Scheduling",
    description:
      "Compute the true critical path from task durations and dependencies using forward/backward pass CPM analysis.",
    workshop: true,
    isNew: true,
    tool: "critical_path",
  },
  {
    id: 31,
    name: "Project Workspace",
    category: "Leadership",
    complexity: "Intermediate",
    readTime: "12 min read",
    tag: "Gantt Timeline",
    description:
      "Plan tasks and milestones on a proportional Gantt timeline computed from start dates, durations, and progress.",
    workshop: true,
    isNew: true,
    tool: "project_workspace",
  },
  {
    id: 32,
    name: "Burn Rate & Runway",
    category: "Strategy",
    complexity: "Intermediate",
    readTime: "10 min read",
    tag: "Financial Oversight",
    description:
      "Model cash balance, revenue, and cost line items to compute net burn, runway, and an optimization opportunity.",
    workshop: true,
    isNew: true,
    tool: "burn_rate",
  },
  {
    id: 33,
    name: "Capacity Planning",
    category: "Leadership",
    complexity: "Intermediate",
    readTime: "10 min read",
    tag: "Resourcing",
    description:
      "Track team allocation against capacity to spot over-allocation and get rebalancing suggestions.",
    workshop: true,
    isNew: true,
    tool: "capacity_planning",
  },
  {
    id: 34,
    name: "Skill Matrix Workshop",
    category: "Leadership",
    complexity: "Intermediate",
    readTime: "10 min read",
    tag: "Team Capability",
    description:
      "Map team proficiency across key skills to surface gaps and single-point-of-failure risks.",
    workshop: true,
    isNew: true,
    tool: "skill_matrix",
  },
  {
    id: 35,
    name: "Unit Economics Workshop",
    category: "Strategy",
    complexity: "Intermediate",
    readTime: "10 min read",
    tag: "Growth Metrics",
    description:
      "Calculate LTV, CAC, and the LTV/CAC efficiency ratio with a live payback period projection.",
    workshop: true,
    isNew: true,
    tool: "unit_economics",
  },
  {
    id: 36,
    name: "360-Degree Feedback Workshop",
    category: "Leadership",
    complexity: "Intermediate",
    readTime: "12 min read",
    tag: "People Development",
    description:
      "Map self vs. external perception with a Johari Window, rate core competencies, and capture keep-doing / start-doing feedback themes.",
    workshop: true,
    isNew: true,
    tool: "three_sixty_feedback",
  },
  {
    id: 37,
    name: "Competitive Benchmarking",
    category: "Strategy",
    complexity: "Intermediate",
    readTime: "12 min read",
    tag: "Market Intelligence",
    description:
      "Score yourself against named competitors across strategic axes and track feature-by-feature parity and gaps.",
    workshop: true,
    isNew: true,
    tool: "competitive_benchmarking",
  },
  {
    id: 38,
    name: "Market Sizing Workshop",
    category: "Strategy",
    complexity: "Beginner",
    readTime: "8 min read",
    tag: "TAM / SAM / SOM",
    description:
      "Define your playing field with a live TAM/SAM/SOM bullseye and a computed market viability score.",
    workshop: true,
    isNew: true,
    tool: "market_sizing",
  },
  {
    id: 39,
    name: "Performance Review",
    category: "Leadership",
    complexity: "Intermediate",
    readTime: "15 min read",
    tag: "1:1 & Reviews",
    description:
      "Rate core competencies, track OKR progress and development goals, and capture private manager notes for a review cycle.",
    workshop: true,
    isNew: true,
    tool: "performance_review",
  },
  {
    id: 40,
    name: "Communication Audit Dashboard",
    category: "Communication",
    complexity: "Intermediate",
    readTime: "10 min read",
    tag: "Content Integrity",
    description:
      "Score clarity, tone, and conciseness across channels, track overused phrases, and turn verbose drafts into tight rewrites.",
    workshop: true,
    isNew: true,
    tool: "communication_audit",
  },
  {
    id: 41,
    name: "PREP Framework Workspace",
    category: "Communication",
    complexity: "Beginner",
    readTime: "6 min read",
    tag: "Executive Messaging",
    description:
      "Structure a persuasive message with Point, Reason, Example, Point — and a live credibility score based on the evidence you provide.",
    workshop: true,
    isNew: true,
    tool: "prep_framework",
  },
  {
    id: 42,
    name: "STAR Framework Workspace",
    category: "Communication",
    complexity: "Beginner",
    readTime: "8 min read",
    tag: "Interview & Portfolio",
    description:
      "Turn an accomplishment into a Situation, Task, Action, Result story with a computed impact score from your metrics and verbs.",
    workshop: true,
    isNew: true,
    tool: "star_framework",
  },
  {
    id: 43,
    name: "BLUF Workshop",
    category: "Communication",
    complexity: "Beginner",
    readTime: "7 min read",
    tag: "Executive Messaging",
    description:
      "Paste a draft and get a deterministic read on verbosity and actionability, plus a Bottom-Line-Up-Front rewrite lead and suggested subject line.",
    workshop: true,
    isNew: true,
    tool: "bluf_workshop",
  },
  {
    id: 44,
    name: "Executive Decision SIR",
    category: "Strategy",
    complexity: "Advanced",
    readTime: "12 min read",
    tag: "Executive Decisions",
    description:
      "Break a high-stakes call into Situation, Impact, and Recommendation, with a computed decision-confidence score and executive summary.",
    workshop: true,
    isNew: true,
    tool: "decision_sir",
  },
  {
    id: 45,
    name: "Tell → Show → Tell Workshop",
    category: "Communication",
    complexity: "Beginner",
    readTime: "8 min read",
    tag: "Presentation Structure",
    description:
      "Structure any presentation with the classic three-part narrative — intro, evidence, and outro — with a computed readiness score.",
    workshop: true,
    isNew: true,
    tool: "tell_show_tell",
  },
  {
    id: 46,
    name: "Initiative Workshop",
    category: "Strategy",
    complexity: "Beginner",
    readTime: "9 min read",
    tag: "Pitch & Narrative",
    description:
      "Turn a raw idea into a high-conviction pitch with the What → Why → How method, a jargon/clarity score, and a synthesized elevator pitch.",
    workshop: true,
    isNew: true,
    tool: "initiative_workshop",
  },
  {
    id: 47,
    name: "Cash Flow Projection",
    category: "Finance",
    complexity: "Intermediate",
    readTime: "10 min read",
    tag: "Financial Planning",
    description:
      "Track a monthly cash ledger with low-cash alerts, plus a sensitivity model for payment delays and cost increases against your runway.",
    workshop: true,
    isNew: true,
    tool: "cash_flow_projection",
  },
  {
    id: 48,
    name: "Empathy Map Workshop",
    category: "Research",
    complexity: "Beginner",
    readTime: "8 min read",
    tag: "User Research",
    description:
      "Map what your target persona says, does, thinks, and feels, then balance it against their pains and desired gains.",
    workshop: true,
    isNew: true,
    tool: "empathy_map",
  },
  {
    id: 49,
    name: "JTBD Workshop",
    category: "Research",
    complexity: "Intermediate",
    readTime: "12 min read",
    tag: "Jobs-to-be-Done",
    description:
      "Capture job stories and functional/emotional/social jobs, then rank opportunities with the Importance-vs-Satisfaction Opportunity Score.",
    workshop: true,
    isNew: true,
    tool: "jtbd_workshop",
  },
  {
    id: 50,
    name: "P&L Forecasting",
    category: "Finance",
    complexity: "Advanced",
    readTime: "12 min read",
    tag: "Financial Planning",
    description:
      "Model 12-month revenue and expense lines under conservative, moderate, or aggressive growth scenarios with live EBITDA and margin tracking.",
    workshop: true,
    isNew: true,
    tool: "pl_forecasting",
  },
  {
    id: 51,
    name: "Customer Journey Workspace",
    category: "Research",
    complexity: "Intermediate",
    readTime: "10 min read",
    tag: "User Research",
    description:
      "Map actions, feelings, and touchpoints across five journey stages, with a computed friction score to surface the riskiest stage.",
    workshop: true,
    isNew: true,
    tool: "customer_journey",
  },
  {
    id: 52,
    name: "User Persona Workshop",
    category: "Research",
    complexity: "Beginner",
    readTime: "9 min read",
    tag: "User Research",
    description:
      "Build a full persona profile — demographics, motivations, a day in the life, pain points — with generated strategy angles for each pain point.",
    workshop: true,
    isNew: true,
    tool: "user_persona",
  },
  {
    id: 53,
    name: "Equity & Cap Table",
    category: "Finance",
    complexity: "Advanced",
    readTime: "12 min read",
    tag: "Ownership & Dilution",
    description:
      "Track shareholder ownership by class, ESOP pool, and simulate a new funding round's dilution impact on every existing holder.",
    workshop: true,
    isNew: true,
    tool: "equity_management",
  },
  {
    id: 54,
    name: "GTM Strategy Workspace",
    category: "Strategy",
    complexity: "Intermediate",
    readTime: "11 min read",
    tag: "Go-to-Market",
    description:
      "Model your sales funnel stage-by-stage with computed conversion rates, track GTM launch checklist progress, and define ideal customer profiles.",
    workshop: true,
    isNew: true,
    tool: "gtm_strategy",
  },
  {
    id: 55,
    name: "Strategic Risk Workspace",
    category: "Strategy",
    complexity: "Intermediate",
    readTime: "10 min read",
    tag: "Risk Management",
    description:
      "Log risks with likelihood and impact to get a computed severity score, a probability/impact heatmap, and category concentration analysis.",
    workshop: true,
    isNew: true,
    tool: "risk_assessment",
  },
  {
    id: 56,
    name: "ICE Scoring Workshop",
    category: "Execution",
    complexity: "Beginner",
    readTime: "6 min read",
    tag: "Prioritization",
    description:
      "Score initiatives on Impact, Confidence, and Ease to compute an ICE score and rank your roadmap by potential.",
    workshop: true,
    isNew: true,
    tool: "ice_scoring",
  },
  {
    id: 57,
    name: "MoSCoW Prioritization Workshop",
    category: "Execution",
    complexity: "Beginner",
    readTime: "8 min read",
    tag: "Prioritization",
    description:
      "Sort scope into Must/Should/Could/Won't Have columns with hour estimates and a computed scope-pressure read on your Must Have load.",
    workshop: true,
    isNew: true,
    tool: "moscow_prioritization",
  },
  {
    id: 58,
    name: "Stakeholder Mapping",
    category: "Strategy",
    complexity: "Beginner",
    readTime: "9 min read",
    tag: "Stakeholder Management",
    description:
      "Plot stakeholders on a Power/Interest matrix with automatic quadrant classification and tailored engagement strategies for each group.",
    workshop: true,
    isNew: true,
    tool: "stakeholder_mapping",
  },
  {
    id: 59,
    name: "Balanced Scorecard Dashboard",
    category: "Strategy",
    complexity: "Advanced",
    readTime: "11 min read",
    tag: "Organizational Health",
    description:
      "Track Financial, Customer, Internal Process, and Learning & Growth KPIs side by side with automatic status scoring and a weighted overall health score.",
    workshop: true,
    isNew: true,
    tool: "balanced_scorecard",
  },
  {
    id: 60,
    name: "Content Calendar Workshop",
    category: "Marketing",
    complexity: "Beginner",
    readTime: "7 min read",
    tag: "Content Planning",
    description:
      "Plan campaign objectives and schedule content across Blog, Social, Email, and Video with completion tracking and channel-load insights.",
    workshop: true,
    isNew: true,
    tool: "content_calendar",
  },
  {
    id: 61,
    name: "McKinsey 7S Workshop",
    category: "Strategy",
    complexity: "Advanced",
    readTime: "10 min read",
    tag: "Organizational Alignment",
    description:
      "Diagnose organizational effectiveness across the 7 interconnected elements — Strategy, Structure, Systems, Shared Values, Style, Staff, and Skills — with a live harmony score.",
    workshop: true,
    isNew: true,
    tool: "mckinsey_7s",
  },
  {
    id: 62,
    name: "Social Media Strategy Lab",
    category: "Marketing",
    complexity: "Intermediate",
    readTime: "9 min read",
    tag: "Channel Strategy",
    description:
      "Map channels, tune voice and tone, define content pillars, and simulate engagement forecasts before you publish.",
    workshop: true,
    isNew: true,
    tool: "social_media_strategy",
  },
  {
    id: 63,
    name: "Customer Success Health Scorecard",
    category: "Operations",
    complexity: "Intermediate",
    readTime: "8 min read",
    tag: "Account Health",
    description:
      "Track account health scores, churn risk, renewal pipeline, and expansion opportunities across your customer portfolio.",
    workshop: true,
    isNew: true,
    tool: "customer_health_scorecard",
  },
  {
    id: 64,
    name: "Employee Onboarding Workshop",
    category: "People",
    complexity: "Beginner",
    readTime: "6 min read",
    tag: "Onboarding",
    description:
      "Structure a phased onboarding roadmap with checklists and progress tracking for new hires.",
    workshop: true,
    isNew: true,
    tool: "onboarding_roadmap",
  },
  {
    id: 65,
    name: "Hiring Scorecard Workshop",
    category: "People",
    complexity: "Intermediate",
    readTime: "8 min read",
    tag: "Candidate Evaluation",
    description:
      "Score candidates against weighted criteria, capture interviewer consensus, and reach a confident hire/no-hire recommendation.",
    workshop: true,
    isNew: true,
    tool: "hiring_scorecard",
  },
  {
    id: 66,
    name: "Lead Management Workspace",
    category: "Sales",
    complexity: "Beginner",
    readTime: "7 min read",
    tag: "Pipeline",
    description:
      "Track inbound leads by source and status, spot your best-converting channel, and manage next actions.",
    workshop: true,
    isNew: true,
    tool: "lead_management",
  },
  {
    id: 67,
    name: "Pricing & Packaging Workshop",
    category: "Strategy",
    complexity: "Advanced",
    readTime: "10 min read",
    tag: "Monetization",
    description:
      "Model tier pricing against projected ARR and benchmark your feature set against competitors.",
    workshop: true,
    isNew: true,
    tool: "pricing_packaging",
  },
  {
    id: 68,
    name: "Recruitment Funnel Workshop",
    category: "People",
    complexity: "Intermediate",
    readTime: "8 min read",
    tag: "Talent Acquisition",
    description:
      "Analyze your hiring funnel from applied to hired, spot the weakest conversion stage, and track source performance.",
    workshop: true,
    isNew: true,
    tool: "recruitment_funnel",
  },
  {
    id: 69,
    name: "Sales Pipeline Kanban",
    category: "Sales",
    complexity: "Intermediate",
    readTime: "8 min read",
    tag: "Deal Flow",
    description:
      "Move deals through a Discovery-to-Closed kanban board with automatic weighted revenue forecasting.",
    workshop: true,
    isNew: true,
    tool: "sales_pipeline",
  },
  {
    id: 70,
    name: "Team Capacity Heatmap",
    category: "Operations",
    complexity: "Intermediate",
    readTime: "8 min read",
    tag: "Resource Planning",
    description:
      "Visualize weekly team utilization by department, flag overloaded teams, and forecast headcount gaps.",
    workshop: true,
    isNew: true,
    tool: "team_capacity_heatmap",
  },
  {
    id: 71,
    name: "Legal & Compliance Hub",
    category: "Operations",
    complexity: "Advanced",
    readTime: "9 min read",
    tag: "Compliance",
    description:
      "Track SOC2 and GDPR readiness checklists, manage a document vault, and stay ahead of regulatory deadlines.",
    workshop: true,
    isNew: true,
    tool: "compliance_hub",
  },
  {
    id: 72,
    name: "Product Analytics Dashboard",
    category: "Product",
    complexity: "Intermediate",
    readTime: "8 min read",
    tag: "Growth Metrics",
    description:
      "Monitor your North Star metric, daily engagement, retention cohorts, and feature adoption in one view.",
    workshop: true,
    isNew: true,
    tool: "product_analytics",
  },
  {
    id: 73,
    name: "Innovation Sandbox",
    category: "Strategy",
    complexity: "Intermediate",
    readTime: "8 min read",
    tag: "Idea Portfolio",
    description:
      "Track product hypotheses through validation scoring, promote winners to the roadmap, and retire dead ends in the framework graveyard.",
    workshop: true,
    isNew: true,
    tool: "innovation_sandbox",
  },
  {
    id: 74,
    name: "Investor Relations Hub",
    category: "Finance",
    complexity: "Advanced",
    readTime: "9 min read",
    tag: "Fundraising",
    description:
      "Manage cap table ownership, build monthly investor updates, maintain a secure document vault, and track stakeholder activity.",
    workshop: true,
    isNew: true,
    tool: "investor_relations",
  },
];

export const goals = [
  {
    id: "perfect-pitch",
    title: "Perfect Pitch",
    description: "Craft compelling narratives for investors.",
    icon: "campaign",
    category: "Narrative",
    frameworkId: 13,
  },
  {
    id: "market-analysis",
    title: "Market Analysis",
    description: "Identify risks and strategic opportunities.",
    icon: "monitoring",
    category: "Strategy",
    frameworkId: 1,
  },
  {
    id: "ideation-session",
    title: "Ideation Session",
    description: "Generate and filter high-impact ideas.",
    icon: "lightbulb",
    category: "Problem Solving",
    frameworkId: 12,
  },
  {
    id: "problem-solving",
    title: "Problem Solving",
    description: "Deconstruct complex roadblocks quickly.",
    icon: "bolt",
    category: "Problem Solving",
    frameworkId: 11,
  },
];
