export const frameworks = [
  {
    id: 1,
    name: "SWOT Analysis",
    category: "Strategy",
    complexity: "Beginner",
    readTime: "15 min read",
    tag: "Strategic Planning",
    description:
      "Master your environment by identifying Strengths, Weaknesses, Opportunities, and Threats. The foundational tool for every high-stakes decision.",
    featured: true,
    workshop: true,
    tool: "swot",
  },
  {
    id: 2,
    name: "First Principles",
    category: "Strategy",
    complexity: "Intermediate",
    readTime: "10 min read",
    tag: "Strategy",
    description:
      "Breaking down complex problems into basic elements and then reassembling them from the ground up.",
    workshop: true,
    tool: "first_principles",
  },
  {
    id: 3,
    name: "The Hero's Journey",
    category: "Narrative",
    complexity: "Beginner",
    readTime: "8 min read",
    tag: "Narrative",
    description:
      "A structural framework for storytelling used to create compelling brand narratives and product visions.",
  },
  {
    id: 4,
    name: "Cynefin Framework",
    category: "Problem Solving",
    complexity: "Advanced",
    readTime: "15 min read",
    tag: "New Framework",
    description:
      "A decision-making tool used to help managers, policy-makers and others identify how they perceive situations and make sense of their own and other people's behavior.",
    isNew: true,
  },
  {
    id: 5,
    name: "5 Whys",
    category: "Problem Solving",
    complexity: "Beginner",
    readTime: "5 min read",
    tag: "Problem Solving",
    description:
      "An iterative interrogative technique used to explore the cause-and-effect relationships underlying a problem.",
  },
  {
    id: 6,
    name: "STAR Method",
    category: "Narrative",
    complexity: "Beginner",
    readTime: "6 min read",
    tag: "Communication",
    description: "Structure your responses to showcase leadership and impact under pressure.",
  },
  {
    id: 7,
    name: "Minto Pyramid",
    category: "Narrative",
    complexity: "Intermediate",
    readTime: "12 min read",
    tag: "Logical Thinking",
    description: "The gold standard for top-down logic and effective executive communication.",
    workshop: true,
    tool: "pyramid",
  },
  {
    id: 8,
    name: "Eisenhower Matrix",
    category: "Leadership",
    complexity: "Beginner",
    readTime: "5 min read",
    tag: "Leadership",
    description: "Prioritize what matters by sorting tasks along urgency and importance.",
  },
  {
    id: 9,
    name: "Porter's Five Forces",
    category: "Strategy",
    complexity: "Advanced",
    readTime: "14 min read",
    tag: "Strategy",
    description: "Analyze the competitive intensity and attractiveness of an industry.",
  },
  {
    id: 10,
    name: "OKR Planning",
    category: "Leadership",
    complexity: "Intermediate",
    readTime: "9 min read",
    tag: "Leadership",
    description: "Set ambitious objectives with measurable key results to align teams.",
  },
  {
    id: 11,
    name: "Issue Tree Builder",
    category: "Problem Solving",
    complexity: "Intermediate",
    readTime: "12 min read",
    tag: "Problem Solving",
    description:
      "Break a root question into mutually exclusive, collectively exhaustive branches on a pannable, zoomable canvas.",
    workshop: true,
    tool: "issue_tree",
  },
  {
    id: 12,
    name: "MECE Workspace",
    category: "Problem Solving",
    complexity: "Intermediate",
    readTime: "10 min read",
    tag: "Problem Solving",
    description:
      "Decompose a core problem into categories with live overlap and gap auditing, so nothing is double-counted or missed.",
    workshop: true,
    tool: "mece",
  },
  {
    id: 13,
    name: "SCQA Storytelling",
    category: "Narrative",
    complexity: "Beginner",
    readTime: "8 min read",
    tag: "Narrative",
    description:
      "Structure a tight pitch narrative — Situation, Complication, Question, Answer — with a live preview as you write.",
    workshop: true,
    tool: "scqa",
  },
  {
    id: 14,
    name: "Logic Tree Workshop",
    category: "Problem Solving",
    complexity: "Advanced",
    readTime: "14 min read",
    tag: "Diagnostics",
    description:
      "Diagnose symptoms or stress-test decisions on a branching canvas with live path-coverage and logic-fallacy scanning.",
    workshop: true,
    isNew: true,
    tool: "logic_tree",
  },
  {
    id: 15,
    name: "Systems Thinking Workspace",
    category: "Strategy",
    complexity: "Advanced",
    readTime: "18 min read",
    tag: "Causal Loop Canvas",
    description:
      "Map stocks, flows, and reinforcing/balancing feedback loops, then let the Delay/Feedback Analyzer surface leverage points.",
    workshop: true,
    isNew: true,
    tool: "systems_thinking",
  },
  {
    id: 16,
    name: "Hypothesis-Driven Thinking",
    category: "Strategy",
    complexity: "Intermediate",
    readTime: "12 min read",
    tag: "Validation",
    description:
      "Turn a business assumption into a testable hypothesis, design the test, and track confidence as evidence comes in.",
    workshop: true,
    isNew: true,
    tool: "hypothesis",
  },
  {
    id: 17,
    name: "GE McKinsey Matrix",
    category: "Strategy",
    complexity: "Advanced",
    readTime: "14 min read",
    tag: "Portfolio Analysis",
    description:
      "Plot business units on a 3x3 industry attractiveness vs. competitive strength grid to guide invest, hold, or divest decisions.",
    workshop: true,
    isNew: true,
    tool: "ge_mckinsey",
  },
  {
    id: 18,
    name: "Three Horizons Framework",
    category: "Strategy",
    complexity: "Advanced",
    readTime: "12 min read",
    tag: "Portfolio Planning",
    description:
      "Balance current-core, emerging, and future-option initiatives on a value-vs-time map with target allocation tracking.",
    workshop: true,
    isNew: true,
    tool: "three_horizons",
  },
  {
    id: 19,
    name: "Porter's Generic Strategies",
    category: "Strategy",
    complexity: "Intermediate",
    readTime: "10 min read",
    tag: "Competitive Strategy",
    description:
      "Define your strategic scope and advantage — Cost Leadership, Differentiation, or a Focused variant — and benchmark competitors.",
    workshop: true,
    isNew: true,
    tool: "porter",
  },
  {
    id: 20,
    name: "Strategic Choice Cascade",
    category: "Strategy",
    complexity: "Advanced",
    readTime: "16 min read",
    tag: "Playing to Win",
    description:
      "Work through Lafley & Martin's five cascading strategy choices, from Winning Aspiration down to Management Systems.",
    workshop: true,
    isNew: true,
    tool: "strategic_cascade",
  },
  {
    id: 21,
    name: "Core Competency Auditor",
    category: "Strategy",
    complexity: "Intermediate",
    readTime: "10 min read",
    tag: "Competitive Advantage",
    description:
      "Audit your capabilities against the Valuable, Unique, and Extendable test to find your true competitive moat.",
    workshop: true,
    isNew: true,
    tool: "core_competency",
  },
  {
    id: 22,
    name: "Lean Canvas Workshop",
    category: "Strategy",
    complexity: "Beginner",
    readTime: "10 min read",
    tag: "Business Model",
    description:
      "Sketch your business model across all nine Lean Canvas blocks, from Problem and Solution to Cost Structure and Revenue Streams.",
    workshop: true,
    isNew: true,
    tool: "lean_canvas",
  },
  {
    id: 23,
    name: "VRIO Analysis Workshop",
    category: "Strategy",
    complexity: "Advanced",
    readTime: "12 min read",
    tag: "Resource-Based View",
    description:
      "Test resources against Valuable, Rare, Inimitable, and Organized hurdles to determine sustained competitive advantage.",
    workshop: true,
    isNew: true,
    tool: "vrio",
  },
  {
    id: 24,
    name: "OKR Workshop",
    category: "Leadership",
    complexity: "Intermediate",
    readTime: "10 min read",
    tag: "Goal Setting",
    description:
      "Set an ambitious objective and track measurable key results with live confidence and progress tracking.",
    workshop: true,
    isNew: true,
    tool: "okr",
  },
  {
    id: 25,
    name: "Product Roadmap Workshop",
    category: "Leadership",
    complexity: "Intermediate",
    readTime: "12 min read",
    tag: "Execution",
    description:
      "Plan milestones across a four-quarter horizon with category tags, progress tracking, and roadmap health insights.",
    workshop: true,
    isNew: true,
    tool: "product_roadmap",
  },
  {
    id: 26,
    name: "Project Charter Workshop",
    category: "Leadership",
    complexity: "Intermediate",
    readTime: "14 min read",
    tag: "Project Initiation",
    description:
      "Define purpose, measurable objectives, milestones, success criteria, risks, and requirements for a new initiative.",
    workshop: true,
    isNew: true,
    tool: "project_charter",
  },
  {
    id: 27,
    name: "RACI Matrix Workshop",
    category: "Leadership",
    complexity: "Intermediate",
    readTime: "10 min read",
    tag: "Responsibility Assignment",
    description:
      "Clarify who is Responsible, Accountable, Consulted, and Informed across your cross-functional team.",
    workshop: true,
    isNew: true,
    tool: "raci",
  },
  {
    id: 28,
    name: "Retrospective Workshop",
    category: "Leadership",
    complexity: "Beginner",
    readTime: "8 min read",
    tag: "Team Health",
    description:
      "Run a Start, Stop, Continue retrospective with sticky-note voting and a shared action item checklist.",
    workshop: true,
    isNew: true,
    tool: "retrospective",
  },
  {
    id: 29,
    name: "Sprint Planning Workshop",
    category: "Leadership",
    complexity: "Intermediate",
    readTime: "10 min read",
    tag: "Agile",
    description:
      "Move stories from the product backlog into the sprint backlog with live capacity utilization and sprint health.",
    workshop: true,
    isNew: true,
    tool: "sprint_planning",
  },
  {
    id: 30,
    name: "Critical Path Analysis Workshop",
    category: "Leadership",
    complexity: "Advanced",
    readTime: "14 min read",
    tag: "Project Scheduling",
    description:
      "Compute the true critical path from task durations and dependencies using forward/backward pass CPM analysis.",
    workshop: true,
    isNew: true,
    tool: "critical_path",
  },
  {
    id: 31,
    name: "Project Workspace",
    category: "Leadership",
    complexity: "Intermediate",
    readTime: "12 min read",
    tag: "Gantt Timeline",
    description:
      "Plan tasks and milestones on a proportional Gantt timeline computed from start dates, durations, and progress.",
    workshop: true,
    isNew: true,
    tool: "project_workspace",
  },
  {
    id: 32,
    name: "Burn Rate & Runway",
    category: "Strategy",
    complexity: "Intermediate",
    readTime: "10 min read",
    tag: "Financial Oversight",
    description:
      "Model cash balance, revenue, and cost line items to compute net burn, runway, and an optimization opportunity.",
    workshop: true,
    isNew: true,
    tool: "burn_rate",
  },
  {
    id: 33,
    name: "Capacity Planning",
    category: "Leadership",
    complexity: "Intermediate",
    readTime: "10 min read",
    tag: "Resourcing",
    description:
      "Track team allocation against capacity to spot over-allocation and get rebalancing suggestions.",
    workshop: true,
    isNew: true,
    tool: "capacity_planning",
  },
  {
    id: 34,
    name: "Skill Matrix Workshop",
    category: "Leadership",
    complexity: "Intermediate",
    readTime: "10 min read",
    tag: "Team Capability",
    description:
      "Map team proficiency across key skills to surface gaps and single-point-of-failure risks.",
    workshop: true,
    isNew: true,
    tool: "skill_matrix",
  },
  {
    id: 35,
    name: "Unit Economics Workshop",
    category: "Strategy",
    complexity: "Intermediate",
    readTime: "10 min read",
    tag: "Growth Metrics",
    description:
      "Calculate LTV, CAC, and the LTV/CAC efficiency ratio with a live payback period projection.",
    workshop: true,
    isNew: true,
    tool: "unit_economics",
  },
];

export const goals = [
  {
    id: "perfect-pitch",
    title: "Perfect Pitch",
    description: "Craft compelling narratives for investors.",
    icon: "campaign",
    category: "Narrative",
    frameworkId: 13,
  },
  {
    id: "market-analysis",
    title: "Market Analysis",
    description: "Identify risks and strategic opportunities.",
    icon: "monitoring",
    category: "Strategy",
    frameworkId: 1,
  },
  {
    id: "ideation-session",
    title: "Ideation Session",
    description: "Generate and filter high-impact ideas.",
    icon: "lightbulb",
    category: "Problem Solving",
    frameworkId: 12,
  },
  {
    id: "problem-solving",
    title: "Problem Solving",
    description: "Deconstruct complex roadblocks quickly.",
    icon: "bolt",
    category: "Problem Solving",
    frameworkId: 11,
  },
];
